# Generated by Django 2.0.1 on 2018-02-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitlefile',
            old_name='substitle_download_link',
            new_name='subtitle_download_link',
        ),
        migrations.RenameField(
            model_name='subtitlefile',
            old_name='substitle_name',
            new_name='subtitle_name',
        ),
    ]
